### ISSUE TITLE
real-debrid no saw elsewhere to configuration

### ISSUE THREAD

**Issue by ericvlog** [Sam-Max/plugin.video.jacktook#1]
hello, where to setting the real-debrid ya?

i manage to play movies using jackett but i no saw where to set the real-debrid api key or authorized .

when i exited the movies, i choose keep the torrent, it back to that movies list by search again jackett for list out the torrent list, it should be back without searching again untill we reenter the movies again for best result. 

btw prowlarr index id is id of the number in specifier index? how to i use multiple index ? 

anime seem like have problem when searching...it show the request to jackett failed.

Thanks for wonderful addons

**Comment by Sam-Max** [comment]
Hi, install directly from zip file to get last version, as I need to update the repository. Get zip file from releases, last version es 0.1.2

**Comment by ericvlog** [comment]
hello, at debrid there i put my real-debrid api token from https://real-debrid.com/apitoken then click on Authorize but it state jacktook error.......

**Comment by ericvlog** [comment]
after install the zip from release i even cannot open the jacktook addon.....

**Comment by Sam-Max** [comment]
> hello, at debrid there i put my real-debrid api token from https://real-debrid.com/apitoken then click on Authorize but it state jacktook error.......

Leave blank, when you click authorize button and finish, it will fill automatically

**Comment by Sam-Max** [comment]
> after install the zip from release i even cannot open the jacktook addon.....

try close kodi and open again, and install the zip and make sure to have an activate internet connection when open addon

**Comment by ericvlog** [comment]
dunno what happen i try uninstall and restart kodi to install but also failed open , then i when to repo there for install just notice you update already inside repo.

maybe i restart my windows and test.

**Comment by ericvlog** [comment]
i think new version have problem i test on my android phone also same.....

**Comment by Sam-Max** [comment]
write me here @sammax09 if you have telegram app

**Comment by saxoloman** [comment]
@Sam-Max 
i have the same problem.
when i click authorize there is no popup for https://real-debrid.com/device
and if i enter my api key above in the addon settings i get an error...
and any version after 1.0 is not working for me. it refuses to start and throws up error

edit , i added log
https://paste.kodi.tv/ezeqivoyat

it seems to be torres addon is missing. but if i use real debrid it shouldn't be necessary right ?

**Comment by saxoloman** [comment]
@Sam-Max 
after installing torres 
jacktook latest addon will start without error but real debrid authorize button still throws up an error

jacktook error
"error":null
"error_code":null
and kodi error
Error: argument of type 'NoneType' is not iterable

after i press ok on kodi error i can see real debrid window for authozitaion but only for a split of a seccond and then it dissapears

here is debug log it its of any help

https://paste.kodi.tv/betumurofo

**Comment by Sam-Max** [comment]
> @Sam-Max after installing torres jacktook latest addon will start without error but real debrid authorize button still throws up an error
> 
> jacktook error "error":null "error_code":null and kodi error Error: argument of type 'NoneType' is not iterable
> 
> after i press ok on kodi error i can see real debrid window for authozitaion but only for a split of a seccond and then it dissapears
> 
> here is debug log it its of any help
> 
> https://paste.kodi.tv/betumurofo

Hi, thanks for reporting. The error is fixed now on 0.1.3.

**Comment by saxoloman** [comment]
@Sam-Max 
hi,thank you for taking time to fix this 
it works now, i can successfully add my real debrid account.
but now there is new issue. whenever i search for something using prowlarr i get message in top right
No debrid results
I am searching for very popular titles that i know are cached in real debrid so there must be results

if i switch to torrest then i can get results with prowlarr and i can play without problems.  

here is a log
https://paste.kodi.tv/vuteposequ

**Comment by Sam-Max** [comment]
> @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> 
> if i switch to torrest then i can get results with prowlarr and i can play without problems.
> 
> here is a log https://paste.kodi.tv/vuteposequ

Did you try to use jackett? I need to polish more prowlarr to get better results.

**Comment by saxoloman** [comment]
> > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > here is a log https://paste.kodi.tv/vuteposequ
> 
> Did you try to use jackett? I need to polish more prowlarr to get better results.

Ok I installed jackett for funn to see if it will work but sadly i get the same error
and again when i select torrent client to torres instead of debrid i can get the results

**Comment by Sam-Max** [comment]
> > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > here is a log https://paste.kodi.tv/vuteposequ
> > 
> > 
> > Did you try to use jackett? I need to polish more prowlarr to get better results.
> 
> Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results

I get many cached when using debrid with jackett, which trackers are you using?

**Comment by Sam-Max** [comment]
> > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > here is a log https://paste.kodi.tv/vuteposequ
> > 
> > 
> > Did you try to use jackett? I need to polish more prowlarr to get better results.
> 
> Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results

write me here https://t.me/sammax09 if you have Telegram app to help you better

**Comment by Sam-Max** [comment]
> > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > here is a log https://paste.kodi.tv/vuteposequ
> > 
> > 
> > Did you try to use jackett? I need to polish more prowlarr to get better results.
> 
> Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results

I saw now what is the problem. I will fix as soon as posible, sorry

**Comment by saxoloman** [comment]
> > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > here is a log https://paste.kodi.tv/vuteposequ
> > > 
> > > 
> > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > 
> > 
> > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> 
> I saw now what is the problem. I will fix as soon as posible, sorry

awesome
thanks alot .
as a test i addedd all indexers that have movie tag in jackett
and i got 1 cached result XD
https://postimg.cc/q6vsf9Mj
https://postimg.cc/Wh4nxJdT

**Comment by Sam-Max** [comment]
> > > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > > here is a log https://paste.kodi.tv/vuteposequ
> > > > 
> > > > 
> > > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > > 
> > > 
> > > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> > 
> > 
> > I saw now what is the problem. I will fix as soon as posible, sorry
> 
> awesome thanks alot . as a test i addedd all indexers that have movie tag in jackett and i got 1 cached result XD https://postimg.cc/q6vsf9Mj https://postimg.cc/Wh4nxJdT

I made a new commit fixing the issue. Download project as zip file and update on kodi. 

And it is not a good idea to add many indexers as it will slow searching a lot and select indexers that give you magnet instead of torrent files also for fastest search

**Comment by saxoloman** [comment]
> > > > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > > > here is a log https://paste.kodi.tv/vuteposequ
> > > > > 
> > > > > 
> > > > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > > > 
> > > > 
> > > > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> > > 
> > > 
> > > I saw now what is the problem. I will fix as soon as posible, sorry
> > 
> > 
> > awesome thanks alot . as a test i addedd all indexers that have movie tag in jackett and i got 1 cached result XD https://postimg.cc/q6vsf9Mj https://postimg.cc/Wh4nxJdT
> 
> I made a new commit fixing the issue. Download project as zip file and update on kodi.
> 
> And it is not a good idea to add many indexers as it will slow searching a lot

thank you
i tried the latest zip,
it works but only 
torrentgalaxy and rutor are showing cached files :/

**Comment by Sam-Max** [comment]
> > > > > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > > > > here is a log https://paste.kodi.tv/vuteposequ
> > > > > > 
> > > > > > 
> > > > > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > > > > 
> > > > > 
> > > > > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> > > > 
> > > > 
> > > > I saw now what is the problem. I will fix as soon as posible, sorry
> > > 
> > > 
> > > awesome thanks alot . as a test i addedd all indexers that have movie tag in jackett and i got 1 cached result XD https://postimg.cc/q6vsf9Mj https://postimg.cc/Wh4nxJdT
> > 
> > 
> > I made a new commit fixing the issue. Download project as zip file and update on kodi.
> > And it is not a good idea to add many indexers as it will slow searching a lot
> 
> thank you i tried the latest zip, it works but only torrentgalaxy and rutor are showing cached files :/

Maybe you need to increase on setting the number of results to get, by default is 10.

**Comment by saxoloman** [comment]
> > > > > > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > > > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > > > > > here is a log https://paste.kodi.tv/vuteposequ
> > > > > > > 
> > > > > > > 
> > > > > > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > > > > > 
> > > > > > 
> > > > > > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> > > > > 
> > > > > 
> > > > > I saw now what is the problem. I will fix as soon as posible, sorry
> > > > 
> > > > 
> > > > awesome thanks alot . as a test i addedd all indexers that have movie tag in jackett and i got 1 cached result XD https://postimg.cc/q6vsf9Mj https://postimg.cc/Wh4nxJdT
> > > 
> > > 
> > > I made a new commit fixing the issue. Download project as zip file and update on kodi.
> > > And it is not a good idea to add many indexers as it will slow searching a lot
> > 
> > 
> > thank you i tried the latest zip, it works but only torrentgalaxy and rutor are showing cached files :/
> 
> Maybe you need to increase on setting the number of results to get, by default is 10.

tried it with 100, but still only like 5 results from torrentgalaxy

**Comment by Sam-Max** [comment]
> > > > > > > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > > > > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > > > > > > here is a log https://paste.kodi.tv/vuteposequ
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > > > > > > 
> > > > > > > 
> > > > > > > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> > > > > > 
> > > > > > 
> > > > > > I saw now what is the problem. I will fix as soon as posible, sorry
> > > > > 
> > > > > 
> > > > > awesome thanks alot . as a test i addedd all indexers that have movie tag in jackett and i got 1 cached result XD https://postimg.cc/q6vsf9Mj https://postimg.cc/Wh4nxJdT
> > > > 
> > > > 
> > > > I made a new commit fixing the issue. Download project as zip file and update on kodi.
> > > > And it is not a good idea to add many indexers as it will slow searching a lot
> > > 
> > > 
> > > thank you i tried the latest zip, it works but only torrentgalaxy and rutor are showing cached files :/
> > 
> > 
> > Maybe you need to increase on setting the number of results to get, by default is 10.
> 
> tried it with 100, but still only like 5 results from torrentgalaxy

delete first all cache on addon settings, and then search again, because if you search same movie or tv will give you old result

**Comment by saxoloman** [comment]
> > > > > > > > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > > > > > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > > > > > > > here is a log https://paste.kodi.tv/vuteposequ
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> > > > > > > 
> > > > > > > 
> > > > > > > I saw now what is the problem. I will fix as soon as posible, sorry
> > > > > > 
> > > > > > 
> > > > > > awesome thanks alot . as a test i addedd all indexers that have movie tag in jackett and i got 1 cached result XD https://postimg.cc/q6vsf9Mj https://postimg.cc/Wh4nxJdT
> > > > > 
> > > > > 
> > > > > I made a new commit fixing the issue. Download project as zip file and update on kodi.
> > > > > And it is not a good idea to add many indexers as it will slow searching a lot
> > > > 
> > > > 
> > > > thank you i tried the latest zip, it works but only torrentgalaxy and rutor are showing cached files :/
> > > 
> > > 
> > > Maybe you need to increase on setting the number of results to get, by default is 10.
> > 
> > 
> > tried it with 100, but still only like 5 results from torrentgalaxy
> 
> delete first all cache on addon settings, and then search again, because if you search same movie or tv will give you old result

of course i do that all the time or i try a new movie that i didnt search for before.
tomorrow i will do fresh install of kodi and see if it helps.

Thanks again 
i love your addon it has so much potential

**Comment by Sam-Max** [comment]
> > > > > > > > > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > > > > > > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > > > > > > > > here is a log https://paste.kodi.tv/vuteposequ
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I saw now what is the problem. I will fix as soon as posible, sorry
> > > > > > > 
> > > > > > > 
> > > > > > > awesome thanks alot . as a test i addedd all indexers that have movie tag in jackett and i got 1 cached result XD https://postimg.cc/q6vsf9Mj https://postimg.cc/Wh4nxJdT
> > > > > > 
> > > > > > 
> > > > > > I made a new commit fixing the issue. Download project as zip file and update on kodi.
> > > > > > And it is not a good idea to add many indexers as it will slow searching a lot
> > > > > 
> > > > > 
> > > > > thank you i tried the latest zip, it works but only torrentgalaxy and rutor are showing cached files :/
> > > > 
> > > > 
> > > > Maybe you need to increase on setting the number of results to get, by default is 10.
> > > 
> > > 
> > > tried it with 100, but still only like 5 results from torrentgalaxy
> > 
> > 
> > delete first all cache on addon settings, and then search again, because if you search same movie or tv will give you old result
> 
> of course i do that all the time or i try a new movie that i didnt search for before. tomorrow i will do fresh install of kodi and see if it helps.
> 
> Thanks again i love your addon it has so much potential

thanks, let me know when you make the tests

**Comment by Sam-Max** [comment]
> > > > > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > > > > here is a log https://paste.kodi.tv/vuteposequ
> > > > > > 
> > > > > > 
> > > > > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > > > > 
> > > > > 
> > > > > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> > > > 
> > > > 
> > > > I saw now what is the problem. I will fix as soon as posible, sorry
> > > 
> > > 
> > > awesome thanks alot . as a test i addedd all indexers that have movie tag in jackett and i got 1 cached result XD https://postimg.cc/q6vsf9Mj https://postimg.cc/Wh4nxJdT
> > 
> > 
> > I made a new commit fixing the issue. Download project as zip file and update on kodi.
> > And it is not a good idea to add many indexers as it will slow searching a lot
> 
> thank you i tried the latest zip, it works but only torrentgalaxy and rutor are showing cached files :/

I will release an update soon that will fix not showing results from some trackers, be ready to test

**Comment by saxoloman** [comment]
> > > > > > > > @Sam-Max hi,thank you for taking time to fix this it works now, i can successfully add my real debrid account. but now there is new issue. whenever i search for something using prowlarr i get message in top right No debrid results I am searching for very popular titles that i know are cached in real debrid so there must be results
> > > > > > > > if i switch to torrest then i can get results with prowlarr and i can play without problems.
> > > > > > > > here is a log https://paste.kodi.tv/vuteposequ
> > > > > > > 
> > > > > > > 
> > > > > > > Did you try to use jackett? I need to polish more prowlarr to get better results.
> > > > > > 
> > > > > > 
> > > > > > Ok I installed jackett for funn to see if it will work but sadly i get the same error and again when i select torrent client to torres instead of debrid i can get the results
> > > > > 
> > > > > 
> > > > > I saw now what is the problem. I will fix as soon as posible, sorry
> > > > 
> > > > 
> > > > awesome thanks alot . as a test i addedd all indexers that have movie tag in jackett and i got 1 cached result XD https://postimg.cc/q6vsf9Mj https://postimg.cc/Wh4nxJdT
> > > 
> > > 
> > > I made a new commit fixing the issue. Download project as zip file and update on kodi.
> > > And it is not a good idea to add many indexers as it will slow searching a lot
> > 
> > 
> > thank you i tried the latest zip, it works but only torrentgalaxy and rutor are showing cached files :/
> 
> I will release an update soon that will fix not showing results from some trackers, be ready to test

Alright i just got home.
i will test as soon as you release

**Comment by saxoloman** [comment]
with latest version error pops up
TypeError: cannot unpack non-iterable NoneType object

part od log:
024-02-08 20:32:52.581 T:3516     info <general>: [JACKTOOK] Could not get final redirect location for URI https://kickasstorrents.to/wonka-2023-1080p-web-h264-groovyturquoiseoompaloompafromthechocolatefactory-tgx-t5964140.html
2024-02-08 20:32:52.584 T:3516    error <general>: ERROR:root:Caught exception:
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.video.jacktook\resources\lib\navigation.py", line 601, in run
                                                       plugin.run()
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.video.jacktook\resources\lib\navigation.py", line 238, in search
                                                       deb_cached_results = check_debrid_cached(p_results, rd_client, p_dialog)
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\plugin.video.jacktook\resources\lib\utils.py", line 650, in check_debrid_cached
                                                       magnet, infoHash = get_magnet_from_uri(downloadUrl)
                                                   TypeError: cannot unpack non-iterable NoneType object

**Comment by Sam-Max** [comment]
Test now with new commit

**Comment by Sam-Max** [comment]
I made a new commit handling the first error. About the spinning icon that keeps showing, it should be fixed if you close kodi and open again when you update the addon.

**Comment by saxoloman** [comment]
> I made a new commit handling the first error. About the spinning icon that keeps showing, it should be fixed if you close kodi and open again when you update the addon.

thank you
no more errors and results are very acceptable i got over 30 results
still no valid search results from kickass. 1337 bitsearch piratebay and so on...but its not that important
at this current state addon is usable to me

**Comment by Sam-Max** [comment]
> rrent state addon is usable to

bitsearch and piratebay should work fine. I tried with first one today. Try later to make a test with a prowlarr with only bitsearch or piratebay  added.

**Comment by Sam-Max** [comment]
> ok i will try prowlarr later but now with jackett i enable only 1337x Public | BitSearch Public | kickasstorrents.to Public | kickasstorrents.ws Public | The Pirate Bay Public
> 
> i searched first 4 movies Aqua man and the lost kingdom - no cached results The beakeeper - no cached results or wrong results from kickass The marvels - kickass results but all are for daredevil tv show and a game. https://postimg.cc/KK7NyZN7 Wonka - no results
> 
> **and log is spamed with** info : [JACKTOOK] Could not get final redirect location for URI https://kickasstorrents.to/wonka-2023-1080p-web-dl-ddp5-1-atmos-h-264-flux-t5964254.html nfo : [JACKTOOK] Could not get final redirect location for URI [https://itorrents.org/torrent/39F39D1C2637FDE8CBB62F5F4B84F595B187B0D7.torrent?title=[Bitsearch.to]Wonka%20(2023)%20[Bluray%201080p][Esp]](https://itorrents.org/torrent/39F39D1C2637FDE8CBB62F5F4B84F595B187B0D7.torrent?title=%5BBitsearch.to%5DWonka%20(2023)%20%5BBluray%201080p%5D%5BEsp%5D)
> 
> i will edit later when i test prowlarr
> 
> ok with prowlarr same settings as jackett i get no results for any of searches and log is spamed with
> 
> 2024-02-08 23:06:44.994 T:1460 warning : CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running 2024-02-08 23:07:05.458 T:5592 info : Skipped 14 duplicate messages.. 2024-02-08 23:07:19.751 T:5592 info : [JACKTOOK] Could not get final redirect location for URI https://1337x.torrentbay.st/torrent/5976438/Aquaman-and-the-Lost-Kingdom-2023-720p-WEBRip-x265-PROTON/ 2024-02-08 23:07:21.870 T:5592 info : [JACKTOOK] Could not get final redirect location for URI https://1337x.torrentbay.st/torrent/5976412/Aquaman-and-the-Lost-Kingdom-2023-720p-H264-Ac3-5-1-Ita-Eng-Sub-Ita-Eng-MIRCrew/ 2024-02-08 23:07:22.874 T:5960 error : XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/search/movie/Aquaman and the Lost Kingdom/572802 2024-02-08 23:07:22.882 T:1460 error : CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/search/movie/Aquaman and the Lost Kingdom/572802) failed
> 
> **and this**
> 
> 2024-02-08 23:10:52.220 T:1460 warning : CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running 2024-02-08 23:10:53.444 T:1460 info : Skipped 8 duplicate messages.. 2024-02-08 23:10:53.444 T:1460 error : Control 55 in window 10025 has been asked to focus, but it can't 2024-02-08 23:11:26.786 T:2504 error : XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/search/movie/Wonka/787699 2024-02-08 23:11:26.788 T:1460 error : CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/search/movie/Wonka/787699) failed 2024-02-08 23:11:28.573 T:2824 info : CActiveAESink::OpenSink - initialize sink
> 
> 2024-02-08 23:14:23.280 T:1460 error : Control 55 in window 10025 has been asked to focus, but it can't 2024-02-08 23:14:31.277 T:1460 warning : CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running 2024-02-08 23:14:48.515 T:3628 info : Skipped 2 duplicate messages.. 2024-02-08 23:14:48.515 T:3628 error : XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/search/movie/Wish/1022796 2024-02-08 23:14:48.528 T:1460 error : CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/search/movie/Wish/1022796) failed 2024-02-08 23:14:50.149 T:2824 info : CActiveAESink::OpenSink - initialize sink
> 
> **prowlarr with only piratebay added** no results and same error 024-02-08 23:34:32.446 T:5684 info : Skipped 3 duplicate messages.. 2024-02-08 23:34:32.446 T:5684 error : XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/search/movie/The Marvels/609681 2024-02-08 23:34:32.454 T:4228 error : CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/search/movie/The Marvels/609681) failed

I added noew Torrentio support also
