### ISSUE TITLE
[REQUEST] Add Elementum as client

### ISSUE THREAD

**Issue by addon-rajada** [Sam-Max/plugin.video.jacktook#11]
Would be possible to add Elementum as torrent client?

play URL: `plugin://plugin.video.elementum/play?uri=<magnet>`

**Comment by asylumexp** [comment]
I'll have a go to see if I can get this, looks like it isnt that big of a change to get in

**Comment by addon-rajada** [comment]
@asylumexp 

Many thanks!
This is very useful for low-memory devices as Elementum can use internal memory or RAM
