### ISSUE TITLE
[Request] TMDB Helper Integration

### ISSUE THREAD

**Issue by jollyhiggler** [Sam-Max/plugin.video.jacktook#13]
I'd be grateful if you could compile a Jacktook TMDB Helper player file for inclusion in [https://github.com/mrgsi/tmdbh.players](https://github.com/mrgsi/tmdbh.players) 

Thanks

**Comment by Sam-Max** [comment]
Yes, I will compile one it is almost finished

**Comment by mrgsi** [comment]
It's now added to the list. Thanks Sam-Max, much appreciated.

**Comment by jollyhiggler** [comment]
Works Great - Many Thanks
