### ISSUE TITLE
[Request] Choose language for TMDb content

### ISSUE THREAD

**Issue by addon-rajada** [Sam-Max/plugin.video.jacktook#15]
Would be possible to choose TMDb API content language?
It would be great to see the titles in pt-BR, or whatever language people want to.

By looking at [tmdb.py](https://github.com/Sam-Max/plugin.video.jacktook/blob/main/resources/lib/tmdbv3api/tmdb.py), seems like the addon is using O.S. environment var for this (?)

Is there a way we can set this at the settings?

**Comment by Sam-Max** [comment]
JT can be added as a player to TMDB Helper Addon. I guess you can choose language there.

**Comment by addon-rajada** [comment]
I hadn't thought of that possibility, thank you!

As this solves the problem I will close the issue, but I still think it would be great to be able to choose the language via settings.xml
