### ISSUE TITLE
[Request] Metadata / Media IDs for Trakt Scrobbling

### ISSUE THREAD

**Issue by jollyhiggler** [Sam-Max/plugin.video.jacktook#17]
Hello,

Would it be feasible to adapt the addon to offer visibility of playing media to [script.trakt](https://github.com/trakt/script.trakt)?

Either by just pulling the relevant Movie / Show / Episode metadata from the TMDb API, or, for greater accuracy, the addition of a ["script.trakt.ids"](https://github.com/trakt/script.trakt/wiki/Providing-id%27s-to-facilitate-scrobbling) pre-playback window property.

Thanks

**Comment by Sam-Max** [comment]
added trakt scrobbling compatibility  3a71725
