### ISSUE TITLE
Torrest hangs while download if I point paths to external USB dongle on my Cube gen3

### ISSUE THREAD

**Issue by puppinoo** [Sam-Max/plugin.video.jacktook#18]
EDIT: sorry if I had to open the issue on torrest repo.

Hi,
Subject basically says all.
I inserted a USB dongle into my Fire TV Cube gen3 usb port.
After it's been recognized I pointed "Download path" and "Torrent folder" to something like: /Storage/**USB id**/Android/org.xbmc.kodi/ first and after I also tried  /Storage/**USB id**/Android/org.xbmc.kodi/files/.
Torrest starts correctly but when I try to download anything, if the file is big, the buffer starts accumulating but suddenly hangs.
Not sure if the issue is related to the USB pointing but I cant try using internal storage cause it's very limited.
Sorry for wasting your time if I did anything wrong.

Regards.

**Comment by Sam-Max** [comment]
Hi @puppinoo, yes, it is better to open the issue on torrest repo, as I am not the developer.
