### ISSUE TITLE
Only 10 seconds of Time Out?

### ISSUE THREAD

**Issue by iz8mbw** [Sam-Max/plugin.video.jacktook#19]
Hello.
Tiring to uae this Addon on Android.
I was not able to have a search result via Jackett due to fixed 10 seconds of Time out.

**Comment by Sam-Max** [comment]
> Hello. Tiring to uae this Addon on Android. I was not able to have a search result via Jackett due to fixed 10 seconds of Time out.

How many trackers did you add to your Jackett?. It is always better to add only 3-4 fours for faster resolve

**Comment by iz8mbw** [comment]
I have more than 4.

**Comment by iz8mbw** [comment]
Hi @Sam-Max there will be the possibility to manually specify in the addon a custom time out value?
In my opinion 10 seconds are not so much. Having a customizable value can fit all users needed.

Thanks!

**Comment by Sam-Max** [comment]
I will increase it on next update

**Comment by iz8mbw** [comment]
So increae but leave it "static" in the code or it will be user customizable?

**Comment by Sam-Max** [comment]
increased to 25s

**Comment by iz8mbw** [comment]
Thanks!
