### ISSUE TITLE
Jackett search: not enought values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by iz8mbw** [Sam-Max/plugin.video.jacktook#20]
I have the error "not enought values to unpack (expected 3, got 1)" while searching using Jackett and no results displayed.

**Comment by Sam-Max** [comment]
I tested now and not getting that error.

**Comment by iz8mbw** [comment]
@Sam-Max try to search using "Direct Search".

**Comment by Sam-Max** [comment]
> @Sam-Max try to search using "Direct Search".

Yeah, I found it now doing more tests, you need to be more specific next time, so I don't get crazy. It is fixed now on latest commit.

**Comment by iz8mbw** [comment]
Yes, sorry. Going to test.
Stay tuned.

**Comment by iz8mbw** [comment]
Now I have: Cannot access local variable 'magnet' where it is not associated with a value

**Comment by iz8mbw** [comment]
Always in "Direct Search".

**Comment by Sam-Max** [comment]
> Now I have: Cannot access local variable 'magnet' where it is not associated with a value

Can you show me your kodi logs?

**Comment by iz8mbw** [comment]
ok

**Comment by Sam-Max** [comment]
fixed now

**Comment by iz8mbw** [comment]
Yes, thanks!

**Comment by iz8mbw** [comment]
@Sam-Max I sent you some messages on Telegram
