### ISSUE TITLE
"Priority foreign language" feature

### ISSUE THREAD

**Issue by RunAway189** [Sam-Max/plugin.video.jacktook#21]
Hello,

I'd like to thank you for your add-on, it simply brought me interest in going back to Kodi since it's based on torrentio search engine. I'm just wondering if it could be ever possible to add the "Priority foreign language feature" like in the original stremio add-on, which could allow us "no-english users" to have something which is fast and reliable. It could be cool to have the flag icons based on the results (just like stremio) but I don't know if this is too complicated.

Thanks for your time and your attention, I'm looking forward to the development of this project!

**Comment by Sam-Max** [comment]
I think that emojis like flags are not supported on Kodi.  I made some tests, and it shows a blank square.

**Comment by addon-rajada** [comment]
Maybe sort results by [flags unicode](https://www.alt-codes.net/flags)? Even whether flags doesn't show up

At least for [Torrentio Brazuca](https://torrentio.strem.fun/brazuca/stream/movie/tt1979376.json), portuguese results has priority and comes first.
So for this provider, just leaving it at original order would be enough.
Don't know if this is valid to others providers.

**Comment by RunAway189** [comment]
> I think that emojis like flags are not supported on Kodi. I made some tests, and it shows a blank square.

It's okay, any other symbol that indicates the language would be absolutely fine. Thanks again for your time, I really hope this feature will come out anytime

**Comment by RunAway189** [comment]
> I think that emojis like flags are not supported on Kodi. I made some tests, and it shows a blank square.

It's okay, I think any other symbol which indicates the language would be absolutely fine. Anyway, thanks a lot again for your time, I really hope that this feature could came out

**Comment by Sam-Max** [comment]
> Maybe sort results by [flags unicode](https://www.alt-codes.net/flags)? Even whether flags doesn't show up
> 
> At least for [Torrentio Brazuca](https://torrentio.strem.fun/brazuca/stream/movie/tt1979376.json), portuguese results has priority and comes first. So for this provider, just leaving it at original order would be enough. Don't know if this is valid to others providers.

good idea or maybe to convert unicode flags to country codes. 

but for sorting results, I would need to find a way for the user to select multiple country on kodi

**Comment by Sam-Max** [comment]
> > I think that emojis like flags are not supported on Kodi. I made some tests, and it shows a blank square.
> 
> It's okay, I think any other symbol which indicates the language would be absolutely fine. Anyway, thanks a lot again for your time, I really hope that this feature could came out

Added on last commit.

**Comment by addon-rajada** [comment]
I found [this](https://gist.github.com/tientran0019/c68b7095976386cf8b1812327228450e) resource which can be used to retrieve language given a flag unicode.
Then would be possible to show detected languages at ListItem label or plot.
Would be also possible to compare with Kodi language and auto-sort results.

**Comment by Sam-Max** [comment]
> I found [this](https://gist.github.com/tientran0019/c68b7095976386cf8b1812327228450e) resource which can be used to retrieve language given a flag unicode. Then would be possible to show detected languages at ListItem label or plot. Would be also possible to compare with Kodi language and auto-sort results.



> I found [this](https://gist.github.com/tientran0019/c68b7095976386cf8b1812327228450e) resource which can be used to retrieve language given a flag unicode. Then would be possible to show detected languages at ListItem label or plot. Would be also possible to compare with Kodi language and auto-sort results.

I am retrieving country code from flag unicode, and showing that on the titles as substitute from emojis. Check the last commit.

**Comment by Sam-Max** [comment]
> I found [this](https://gist.github.com/tientran0019/c68b7095976386cf8b1812327228450e) resource which can be used to retrieve language given a flag unicode. Then would be possible to show detected languages at ListItem label or plot. Would be also possible to compare with Kodi language and auto-sort results.

Any improvements is welcome

**Comment by addon-rajada** [comment]
> > I found [this](https://gist.github.com/tientran0019/c68b7095976386cf8b1812327228450e) resource which can be used to retrieve language given a flag unicode. Then would be possible to show detected languages at ListItem label or plot. Would be also possible to compare with Kodi language and auto-sort results.
> 
> > I found [this](https://gist.github.com/tientran0019/c68b7095976386cf8b1812327228450e) resource which can be used to retrieve language given a flag unicode. Then would be possible to show detected languages at ListItem label or plot. Would be also possible to compare with Kodi language and auto-sort results.
> 
> I am retrieving country code from flag unicode, and showing that on the titles as substitute from emojis. Check the last commit.

I see. I exchanged country code by the language itself at pull-request.
Maybe changes from #24 can close this issue?

**Comment by RunAway189** [comment]
I really don't know how to thank you guys for this crucial feature. I really really appreciate it, I've just tested (version 0.2.1) and it works almost perfectly, now I'm going to explain why "almost".

![Kodi Screenshot 2024 03 15 - 17 47 41 06](https://github.com/Sam-Max/plugin.video.jacktook/assets/90914346/8d9cf6fc-bc3b-4122-816c-a3289c11f7d1)

If I try to set in this way, the "priority" filter doesn't group all the links with the same languages in quality order but they are sorted randomly like you can see on this screenshot

Unfortunately I don't have the proper skills to fix this otherwise I could have already done it. Thanks again!

**Comment by addon-rajada** [comment]
@RunAway189 

You must set `Sort by` to `Language`

Try to use most updated version https://github.com/Sam-Max/plugin.video.jacktook/archive/refs/heads/main.zip while there is no release for 0.2.2

**Comment by RunAway189** [comment]
@addon-rajada 

Yes, I've already noticed that filter option, the thing is that in my opinion that shouldn't exist. Let me explain: the "priority language" tab should already work as "group my selected language results on the top" and then the upper filter "Sort by size, seeds etc." should then re-order all those grouped top results based on what the user have selected there.

At the moment the "sort by language" filter just groups everything exclusively by language+seeds (which is already excellent but it could be optimized even more as I explained. In that way we could have a language+size, language+quality and so on...

Anyway, I'm already happy with this and I cannot wait to set it up my Kodi again!

**Comment by addon-rajada** [comment]
> @addon-rajada
> 
> Yes, I've already noticed that filter option, the thing is that in my opinion that shouldn't exist. Let me explain: the "priority language" tab should already work as "group my selected language results on the top" and then the upper filter "Sort by size, seeds etc." should then re-order all those grouped top results based on what the user have selected there.
> 
> At the moment the "sort by language" filter just groups everything exclusively by language+seeds (which is already excellent but it could be optimized even more as I explained. In that way we could have a language+size, language+quality and so on...
> 
> Anyway, I'm already happy with this and I cannot wait to set it up my Kodi again!

I see, in this case i guess it would be needed a double sorting, one for `sort by` and one for  `language`.
As it's a design thing it's up to @Sam-Max change it or not

**Comment by Sam-Max** [comment]
The problem that I see is that if you group results on top by priority language and after that you sort again for example by seeds, then the top grouped language results can be broken.

I think that solution could be to have two different list, a first one with grouped language results with the language selected by the user and another with the rest, then apply the second sorting to each list individually and keep the first list on top of results.

**Comment by RunAway189** [comment]
> The problem that I see is that if you group results on top by priority language and after that you sort again for example by seeds, then the top grouped language results can be broken.
> 
> I think that solution could be to have two different list, a first one with grouped language results with the language selected by the user and another with the rest, then apply the second sorting to each list individually and keep the first list on top of results.

That could be a great idea as well. I just suggested something which could be optimized a little more but you already achieved a big achievement so far. The fact is that having a good sorting list is crucial if in the future you are going to add a "direct play the first result" feature anytime.

**Comment by Sam-Max** [comment]
resolve b4aafea
