### ISSUE TITLE
Category suggestion 

### ISSUE THREAD

**Issue by icarok99** [Sam-Max/plugin.video.jacktook#25]
Trending (movies and tv shows)

Popular (movies and tv shows)

Top rated (movies and tv shows)

Now playing movies (only movies)

Upcoming movies (only movies)

Tv shows airing today (only tv shows)

Tv shows on the air (only tv shows)

**Comment by Sam-Max** [comment]
Not planning to add all of those, you can use tmdb helper addon to get all those categories
