### ISSUE TITLE
[FIXED] Viewtype

### ISSUE THREAD

**Issue by icarok99** [Sam-Max/plugin.video.jacktook#27]
The addon only has 2 types of views and in one of the views it does not show the content cover.

**Comment by icarok99** [comment]
The landscape view type is also good, there are people who use this view type in TV show episodes.

**Comment by Sam-Max** [comment]
@icarok99 now addon supports all viewtypes, update to latest commit

**Comment by icarok99** [comment]
Thanks @Sam-Max

**Comment by icarok99** [comment]
Poster view type: In the part that shows the seasons, the clearlogo is being displayed.

**Comment by Sam-Max** [comment]
> Poster view type: In the part that shows the seasons, the clearlogo is being displayed.

fixed now
