### ISSUE TITLE
Anime Show Title searched instead of browsed

### ISSUE THREAD

**Issue by DaisyF8** [Sam-Max/plugin.video.jacktook#3]
When going into JT/Anime and clicking an Anime-title JT will start searching instead of opening the show and showing seasons/episodes.

Event in Prowlarr :+1: 
`Searching indexer(s): [Provider Names] for Term: [Anime Title], Offset: 0, Limit: 0, Categories: []`

Categorie should be I think 5000 or 5070 for me but is empty in the event.

EDIT : Kodi 21 Beta 2

**Comment by Sam-Max** [comment]
I am trying to find out how to get season and episodes from anilist API, but have not found yet how to do it. Maybe I need to use another API for anime metadata.

**Comment by DaisyF8** [comment]
Maybe look at the implementation by Otaku ?  They use anilist for watchlist. Github goldenfreddy0703 Hooty repo.

**Comment by DaisyF8** [comment]
Thanks for fixing 👍🏻
