### ISSUE TITLE
Kodi Matrix compatibility

### ISSUE THREAD

**Issue by addon-rajada** [Sam-Max/plugin.video.jacktook#30]
As the VideoInfoTag is something new (Kodi 20+), it would be possible to keep compatibility with Kodi 19?
Currently in Kodi 19 none movie/tvshow ListItem shows up

**Comment by Sam-Max** [comment]
Maybe drop compatibility for kodi 19 would be a good idea. Do you use kodi 19? If so why not use kodi 20?

**Comment by addon-rajada** [comment]
Yeah, i still using it at some devices (lightest I.M.O.), so this compatibility would be great.
I personally think they killed Kodi Matrix too fast. It's still indeed python 3.
I guess just avoid use VideoInfoTag (if version 19) would be enough to make the addon work.

**Comment by Sam-Max** [comment]
Yes, adding a conditional to check kodi version, and if version is less than 20 not to use VideoInfoTag

**Comment by Sam-Max** [comment]
> Yeah, i still using it at some devices (lightest I.M.O.), so this compatibility would be great. I personally think they killed Kodi Matrix too fast. It's still indeed python 3. I guess just avoid use VideoInfoTag (if version 19) would be enough to make the addon work.

Could contact me here: https://t.me/sammax09 ?

**Comment by addon-rajada** [comment]
At first i got the error `Failed to convert to input type to either a std::string or a std::vector`.
But now, last commit version is working flawlessly.

Closing the issue
