### ISSUE TITLE
Support for TorrServer

### ISSUE THREAD

**Issue by puppinoo** [Sam-Max/plugin.video.jacktook#31]
Hi,
Could you consider to support 
https://github.com/YouROK/TorrServer

I'm testing it and it seems very good. Main advantage is that it keeps stream in memory so no issue with filesystems limits.
On PDA official thread https://4pda.to/forum/index.php?showtopic=889960 theres even a tutorial to install server on a FireTv Stick so I guess it's very lightweight. https://4pda.to/forum/index.php?showtopic=889960&st=24880#entry119178423
Unfortunately much of info about it around are in russian.

Thanks.

**Comment by Sam-Max** [comment]
Is there already a kodi addon that use Torrserver?. And also Elementum addon supports in memory streaming.

**Comment by puppinoo** [comment]
> Is there already a kodi addon that use Torrserver?. And also Elementum addon supports in memory streaming.

Hi, thanks for reply,
1) Not that I'm aware of, but there is a very cool soft called "Lampa" https://github.com/yumata/lampa which uses it. It's available on various platforms, even TVOSes like Tizen or WebOS. Android too. To avoid bans the TVOses versions have the Torrent/Parsers sections hidden. They need codes to be unlocked.
2) I admit I'm pretty newbie about torrents so I've never used Elementum for privacy reasons. The cool thing about this one is that the server can be installed on a remote site.
I installed my server on a remote VPS in Netherlands and connect Lampa to use it. I'm testing it and it works. Not sure I can do the same with elementum. The idea is keep locally just the client and use the server elsewhere.
But maybe it's a dumb idea due to inexperience.

Thanks.

**Comment by Sam-Max** [comment]
I was testing Lampa now and it uses Jackett/Prowlarr for torrent sources, similar to Jacktook. And yes running Elementun torrent server/daemon on a remote server it is not an easy thing to do, as it is not designed for that purpose, but you can run very easy Torrest torrent server on a remote vps.

**Comment by puppinoo** [comment]
> I was testing Lampa now and it uses Jackett/Prowlarr for torrent sources, similar to Jacktook. And yes running Elementun torrent server/daemon on a remote server it is not an easy thing to do, as it is not designed for that purpose, but you can run very easy Torrest torrent server on a remote vps.

Thanks for testing,
I tried Torrest but it has no In memory mode (at least not that I'm aware of, please tell me if I'm wrong) and on my FireTV Cube, torents in very big size hanged when file on FS reached 4gb.
 I will test Torrest on my vps.
The good thing about TorrServer is that you can have the best of two worlds: make it work locally on a very limited resources dongle and remotely on a better specs site. Also actually I can even use lampa on my sister's LG CX which is not possible using Torrest but of course this is a very personal and specific need. Just to say.

Thanks.

**Comment by Sam-Max** [comment]
Yes, Torrest has not in memory download, but if you run the torrest server on a remote vps, you can play with no problem videos of any size, as longs as the vps has enough disk space.

**Comment by puppinoo** [comment]
> Yes, Torrest has not in memory download, but if you run the torrest server on a remote vps, you can play with no problem videos of any size, as longs as the vps has enough disk space.

Ill try.
But please if possible look into the possibility to add this one .

Cheers.

**Comment by Sam-Max** [comment]
> > Yes, Torrest has not in memory download, but if you run the torrest server on a remote vps, you can play with no problem videos of any size, as longs as the vps has enough disk space.
> 
> Ill try. But please if possible look into the possibility to add this one .
> 
> Cheers.

It can be done, but that will take time and effort, and I don't feel motivated to do this, and even less when there is already a solution using Torrest

**Comment by puppinoo** [comment]
> > > Yes, Torrest has not in memory download, but if you run the torrest server on a remote vps, you can play with no problem videos of any size, as longs as the vps has enough disk space.
> > 
> > 
> > Ill try. But please if possible look into the possibility to add this one .
> > Cheers.
> 
> It can be done, but that will take time and effort, and not feel motivated to do this, and even less when there is already a solution using Torrest

I totally understand.
Truth Is that I'm pretty happy with my setup and reluctant to change but I have to try Torrest on my VPS, above all because you made me think my actual setup Is probably wrong cause it's still configured in in memory mode when maybe on a VPS it's not necessary.
I'll try Torrest on this weekend 

Thanks

**Comment by Sam-Max** [comment]
On the readme, I have there instructions on how to run with docker the torrest server, very easy to do. And if you have a domain name and reverse proxy on your vps, even better to run torrest server.

**Comment by puppinoo** [comment]
Hi,
Not sure you read here. Just to say I installed torrest-cpp on my VPS and testing it.
My issues so far I hadn't with TorrentServer:
1) Lack of any form of authentication (basic or whatever). I read your issue opened on torrest github about it but unfortunately it's stale.
2) Lack of in memory mode (on my VPS I have very limited storage so I have to choose carefully based on size).
2a) Not sure this is a real issue but sometimes when timeout happens it doesnt delete stale torrent + folders. Can you confirm torrest calculates size on the WHOLE torrent even when you select single episode from a bunch of them?

Still think TorrServer is better but so far so good.

Thanks.

**Comment by Sam-Max** [comment]
Hi Puppinoo, yes, Torrest has not authentication, I finally ended adding authentication to Torrest server by my own, made some modifications to Torrest server repo and used reverse proxy basic auth.

Regarding to vps, do you have more ram than disk space?

**Comment by puppinoo** [comment]
> Hi Puppinoo, yes, Torrest has not authentication, I finally ended adding authentication to Torrest server by my own, made some modifications to Torrest server repo and used reverse proxy basic auth.
> 
> Regarding to vps, do you have more ram than disk space?


Hi,
Thanks for reply.
Not at all,
I actually have 2gb of ram and left about 9.5GB of storage.
But (and I'm not sure about that. I'd have to verify) Torrserver seems clever not to append to old chunks of consumed data but discard older and keep just the stuff I need. 
In fact if I monitor the memory using htop I always see the same amount of ram used.
But maybe it's just me sucking at monitoring. Also this could be the cause of the only serious issue I have with Torrserver. Basically if I pause the stream for more than a few seconds often when I try to resume it stops.

Btw, in this weekend I tested Jacktook + Torrest on vps.
I created a single docker-compose.yml with inside 
gluetun + nordvpn
socks5
torrserver
torrest
jackett
flaresolverr

The great thing of docker networking is that with a single command I can make all the docker inside the compose  pass through gluetun + nordvpn network (which points to a netherlands ip).
So now all the stuff from a US Vps go out using netherlands ip.
I know it's overkill and probably impacts trmendously performances but so far it works. Still testing though.
The main issue I found is not even related to torrest but with the indexers to choose in jackett.
If I choose a "bad one" the search becomes tremendously long (minutes for a single search). So I had to choose very specific indexers (and probably not the best)

Also can you improve Jackett search?
It seems it's very loose with results. The main example is "Barbie".
If I search using Jackett + Lampa results are right on spot with the actual movie.
If I search using JackTook it returns "all kind of sh*t" with even adult content.
Maybe Lampa sends to jacket some kind of unique id so it knows what to look for?

EDIT: I rechecked and it's mostly but not entirely true. If I click on Barbie card it returns Barbie 2023 but also a couple of Barbie 2005 Return of Pegasus. So maybe the id thing is not true. Btw the resusts are much more precise.

I'll keep you updated.

Thanks.

**Comment by Sam-Max** [comment]
Hi @puppinoo , interesting that behavior of TorrServer that keeps the same amount of ram while streaming.  I guess Elementum does the same, but I am not sure.

I have a similar setup like you using gluetun, no performance issue, very good setup. 

And yes, Jackett search on JT actually is using name and not imdb id. It would be a good idea to improve that.

**Comment by puppinoo** [comment]
![Schermata del 2024-03-31 17-42-29](https://github.com/Sam-Max/plugin.video.jacktook/assets/1208875/be6bc068-ed3c-4b8a-a56b-ef98899971bd)
Default is 64mb if im not wrong. On the (russian) official thread there is a tutorial which suggests to raise it to 192mb. I kept the other 2 vaules as default. Not sure if they need to be raised too.

How many indexers you have (which one if I can ask)?
I have 5 (4 US + 1 IT) and search is still not fast as I'd like.
I notice that at start but also when I stop a stream cause it repeats the search.

**Comment by Sam-Max** [comment]
Can you write me here https://t.me/sammax09?

**Comment by Sam-Max** [comment]
0d5ea6dbcf165e4689901e327adb7647fdb47f0e and 4a4dab4156142fa2d8bf0c38d0deaadef2ec5b24 adds supports for TorrServer
