### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by icarok99** [Sam-Max/plugin.video.jacktook#33]
Is there any way to use Elementum + Elementum burst? I like your Addon because unlike others it loads very quickly.

**Comment by icarok99** [comment]
https://github.com/addon-rajada/plugin.video.year-explorer/blob/dfc442116aedafe58e430b0729f9f99d53b9b32c/resources/lib/utils.py#L86

**Comment by Sam-Max** [comment]
> Is there any way to use Elementum + Elementum burst? I like your Addon because unlike others it loads very quickly.

From JT you can only play torrents on Elementum that you got using JT scrapers like torrentio, elfhosted, jackett or prowlarr. For using Elementum Burst you have to use Elementum addon directly

**Comment by icarok99** [comment]
> > Is there any way to use Elementum + Elementum burst? I like your Addon because unlike others it loads very quickly.
> 
> From JT you can only play torrents on Elementum that you got using JT scrapers like torrentio, elfhosted, jackett or prowlarr. For using Elementum Burst you have to use Elementum addon directly

I thought I could do something similar like this Addon where you can use Elementum + Elementum burst.

https://github.com/addon-rajada/plugin.video.year-explorer/blob/main/resources/lib/utils.py


https://github.com/addon-rajada/plugin.video.year-explorer/blob/main/resources/lib/routing.py

![IMG_20240406_130154](https://github.com/Sam-Max/plugin.video.jacktook/assets/46580318/d0ba12d0-5ddb-4651-85f4-d86ca6518448)

**Comment by Sam-Max** [comment]
@addon-rajada is the developer, may he can add to JT the search functionality. Although that would be make JT too dependant on Elementum. 

And what do you mean that JT loads more quickly?

**Comment by icarok99** [comment]
I use the addon as a widget on the skin I use. Then whenever I change tabs the loading is fast.

![Screenshot_2024-04-06-15-20-51-680_org xbmc kodi](https://github.com/Sam-Max/plugin.video.jacktook/assets/46580318/ad054c73-6ad2-482d-b7ba-8b65f859f696)

**Comment by icarok99** [comment]
> @addon-rajada is the developer, may he can add to JT the search functionality. Although that would be make JT too dependant on Elementum.
> 
> And what do you mean that JT loads more quickly?

Yes, but it would have the advantage of activate or disable the provider through Kodi itself.

![Screenshot_2024-04-06-15-40-08-818_org xbmc kodi](https://github.com/Sam-Max/plugin.video.jacktook/assets/46580318/9a624d54-2b2d-4342-a90e-feac73886727)

**Comment by Sam-Max** [comment]
@icarok99 can you write me here https://t.me/sammax09?

**Comment by addon-rajada** [comment]
> > > Is there any way to use Elementum + Elementum burst? I like your Addon because unlike others it loads very quickly.
> > 
> > 
> > From JT you can only play torrents on Elementum that you got using JT scrapers like torrentio, elfhosted, jackett or prowlarr. For using Elementum Burst you have to use Elementum addon directly
> 
> I thought I could do something similar like this Addon where you can use Elementum + Elementum burst.
> 
> https://github.com/addon-rajada/plugin.video.year-explorer/blob/main/resources/lib/utils.py
> 
> https://github.com/addon-rajada/plugin.video.year-explorer/blob/main/resources/lib/routing.py
> 
> ![IMG_20240406_130154](https://private-user-images.githubusercontent.com/46580318/320217717-d0ba12d0-5ddb-4651-85f4-d86ca6518448.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NTQyNzQsIm5iZiI6MTcxMzU1Mzk3NCwicGF0aCI6Ii80NjU4MDMxOC8zMjAyMTc3MTctZDBiYTEyZDAtNWRkYi00NjUxLTg1ZjQtZDg2Y2E2NTE4NDQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE5MTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxOGQ2ODY3MmRhZjIxZTcyMzYyZTIwNjk0OGU2Y2U2ZDc4NTY4YzdlZDY1YjY1YjJlZGZhNGNhNmJmZTkwMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AI86c4H6t1cbbDMy7boJZjvMSlkHSZ8OAxarV31wd8E)

The thing is: by using this method we got a heavy dependence on Elementum in a way that we can't just retrieve the links.

With recent Jacktook modifications, i just made a modified version of Rajada to work with it. It's available [here](https://github.com/addon-rajada/addon-rajada.github.io/tree/main/zips/script.jacktook.rajada).
