### ISSUE TITLE
Addon JT not found

### ISSUE THREAD

**Issue by ladoba** [Sam-Max/plugin.video.jacktook#34]
Hi.
Congrats on the plugin.
I've been using it for a few days, but now when I set anything up, it looks for jacktorr even if it's not installed, if it's installed JT doesn't use torrest. I don't understand what happened now. I deleted Kodi, all its folders , I reinstalled but same error.Torrest addon works,it can connect to remote torrest-cpp server,I see the files.
I'm testing JT,torrest on my macbook before install on my box.
Any idea?

Thanks,
L
<img width="1512" alt="Screenshot 2024-04-17 at 19 35 16" src="https://github.com/Sam-Max/plugin.video.jacktook/assets/122222864/0e5589ed-8736-4cac-8709-4db751cd4839">
<img width="1512" alt="Screenshot 2024-04-17 at 19 35 00" src="https://github.com/Sam-Max/plugin.video.jacktook/assets/122222864/d3847967-deb4-4e53-8ae3-22940639d4f1">

**Comment by ladoba** [comment]
I tried these setups:
v19.5 - 0.2.2 xtremely slow (or search did not work?)
v19.5 - 0.2.4 jacktorr not found
v20.5 - 0.2.2 xtremely slow (or search did not work?)
v20.5 - 0.2.4 jacktorr not found
v21 - 0.2.2 xtremely slow (or search did not work?)
v21 - 0.2.4 jacktorr not found

But I still do not understand,how could I use it yesterday morning..

**Comment by Sam-Max** [comment]
Hi @ladoba the "jacktorr not found" error is happening when you click on Torrents menu section?

**Comment by ladoba** [comment]
Hi @Sam-Max .
Yes.

**Comment by Sam-Max** [comment]
> Hi @Sam-Max . Yes.

I removed Torrest access from Torrents menu sections, and instead added Jacktorr access, a new addon I created for torrent streaming.

**Comment by ladoba** [comment]
I'm sad.Jacktorr only can connect to torrserver and torrserver cannot seed continuously.

**Comment by Sam-Max** [comment]
> I'm sad.Jacktorr only can connect to torrserver and torrserver cannot seed continuously.

you can still access Torrest's torrents from Torrest addon itself and only use JT to play torrents with Torrest

**Comment by Sam-Max** [comment]
> I'm sad.Jacktorr only can connect to torrserver and torrserver cannot seed continuously.

and I think you can still seed with jacktorr, you have to change on server the option to use disk instead of ram

**Comment by ladoba** [comment]
seeding only works during streaming

**Comment by Sam-Max** [comment]
> seeding only works during streaming

but if you don't delete file after streaming, does not keeps seeding?

**Comment by ladoba** [comment]
When you do not streaming the file it does not seeding it.

**Comment by ladoba** [comment]
@Sam-Max 
Do i have to forget the jacktook/torrest collaboration?

**Comment by Sam-Max** [comment]
> @Sam-Max Do i have to forget the jacktook/torrest collaboration?

You can still use Torrest as a client on Jacktook

**Comment by ladoba** [comment]
I cannot use it,still getting addon jacktorr not found error message.

**Comment by Sam-Max** [comment]
> I cannot use it,still getting addon jacktorr not found error message.

What I mean is that you can still use torrest on jacktook as a client to play/stream torrent sources, but you cannot longer access torrest torrents list from menu

**Comment by ladoba** [comment]
Oh okay.Sounds good! Thank you
