### ISSUE TITLE
Direct search bug

### ISSUE THREAD

**Issue by ladoba** [Sam-Max/plugin.video.jacktook#36]
Hi @Sam-Max 
I found a bug.Direct search » tv or movie » find something and play » at the stream end search window pops up » hit cancel or ok » jacktook exits

Thanks,
L

**Comment by ladoba** [comment]
i found one more thing. I use remotely torrest with your addon.If I add .torrent file manually to torrest it downloads every single file what .torrent file contains,BUT if a select a file to stream in jacktook,in this case torrest only dowload the streamed file.could you add this feature to download all files and not just the streamed file please?

**Comment by Sam-Max** [comment]
> i found one more thing. I use remotely torrest with your addon.If I add .torrent file manually to torrest it downloads every single file what .torrent file contains,BUT if a select a file to stream in jacktook,in this case torrest only dowload the streamed file.could you add this feature to download all files and not just the streamed file please?

Hi @ladoba, the purpose of jacktook is to stream the file that you clicked, not to download the entire torrent's files. Besides that, for those who don't have much disk space, that would be also a problem.

**Comment by ladoba** [comment]
an option like in elementum
<img width="869" alt="Screenshot 2024-04-22 at 11 44 17" src="https://github.com/Sam-Max/plugin.video.jacktook/assets/122222864/d9ef2acf-455d-4c56-88b1-40d35ec1e251">
<img width="851" alt="Screenshot 2024-04-22 at 11 44 24" src="https://github.com/Sam-Max/plugin.video.jacktook/assets/122222864/2224fab6-63a3-41f1-9262-48af0ad2852f">
<img width="852" alt="Screenshot 2024-04-22 at 11 44 31" src="https://github.com/Sam-Max/plugin.video.jacktook/assets/122222864/e3029d07-c8f1-4c4e-84c5-6da131289119">

**Comment by ladoba** [comment]
> Hi @Sam-Max I found a bug.Direct search » tv or movie » find something and play » at the stream end search window pops up » hit cancel or ok » jacktook exits
> 
> Thanks, L

Hi @Sam-Max 
Could you check this bug please?
