### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by szur77** [Sam-Max/plugin.video.jacktook#37]
Hello there!

Was looking for a prowlarr addon for Kodi/Elementum and came across your page.

I have both prowlarr and jackett servers running on a Synology NAS on my LAN. After installing and configuring your addon, and leaving only 1 torrent indexer in prowlarr, I permanently get the same error after I attempt a search request. As far as I can see in the prowlarr and jackett history, both prowlarr and jackett receive the search request from jacktook, process it but jacktook is unable to process the reply? Will provide the complete log if necessary. Please advise.

**Comment by szur77** [comment]
Same result after setting up Torrentio as per the instruction below. Looks like a compatibility issue with Kodi 21 on Win 11 ?

https://howtomediacenter.com/en/install-jacktook-kodi-addon/

**Comment by szur77** [comment]
So, after several experiments with Jacktook setup for Torrentio, I've noticed that it works normally with the active VPN connection.

Log without VPN: https://paste.kodi.tv/amejuxafol.kodi
Log with VPN: https://paste.kodi.tv/dejayisage.kodi

Geo block?

**Comment by Sam-Max** [comment]
Hi @szur77 sorry I could not answer before. If you can only access Torrentio with vpn, then your ISP or Torrentio web is banning your IP address.
