### ISSUE TITLE
New Feature 

### ISSUE THREAD

**Issue by ronfrankhill** [Sam-Max/plugin.video.jacktook#38]
Is possible for you to implement trakt.tv ( https://trakt.tv/ ) into it. Please.

**Comment by Sam-Max** [comment]
> Is possible for you to implement trakt.tv ( https://trakt.tv/ ) into it. Please.

Which features of trakt would you like to be added?

**Comment by ronfrankhill** [comment]
Progress TV episode from the user account after signing into trakt.tv but also trakt.tv watchlist for movies and watchlist for TV series from the user account.

**Comment by Sam-Max** [comment]
> watchlist for TV series from the user account.

Ok, I will add those trakt features

**Comment by ronfrankhill** [comment]
Thanks

**Comment by ronfrankhill** [comment]
The trakt.tv is working perfectly. Could you add for trakt.tv called Progress Episode in the TV section. Please.
