### ISSUE TITLE
No results from Prowlarr

### ISSUE THREAD

**Issue by ghost** [Sam-Max/plugin.video.jacktook#40]
Just trying out the NZB. I am running arm64 and I have installed prowlarr. I am only using prowlarr. I have setup the NZBGeek indexer. When I use jacktook, it says searching prowlarr but it doesn't return any results. I have prowlarr running in a terminal and no results show up in the terminal window. I did the search on the NZBGeek website and it has results. I am not sure if my issue is with prowlarr or jacktook or kodi. I didn't setup any applications in prowlarr. Not sure if I need to do this.

**Comment by ghost** [comment]
I did a manual search in prowlarr and the console said a limit of 100 and I saw 100 results. I did the same search with JT and it set the limit to 0 so this is probably why it is returning no results.

**Comment by dinjojo** [comment]
How did you added prowlarr ? Since prowlarr requires authentication how is it working with jacktook

**Comment by Sam-Max** [comment]
> Just trying out the NZB. I am running arm64 and I have installed prowlarr. I am only using prowlarr. I have setup the NZBGeek indexer. When I use jacktook, it says searching prowlarr but it doesn't return any results. I have prowlarr running in a terminal and no results show up in the terminal window. I did the search on the NZBGeek website and it has results. I am not sure if my issue is with prowlarr or jacktook or kodi. I didn't setup any applications in prowlarr. Not sure if I need to do this.

Jacktook does not support NZB only torrents. You cannot get a direct link from an nzb file for streaming.

**Comment by ghost** [comment]
Thanks. I clicked on the DL link in prowlarr and it said that I didn't have servers. I did this after I opened the ticket. I thought NZBGeek provided direct links as I haven't tried newsgroups in years.
