### ISSUE TITLE
Unable to authenticate Prowlarr 

### ISSUE THREAD

**Issue by dinjojo** [Sam-Max/plugin.video.jacktook#41]
Have put in the api key correctly but it keeps failing with authentication error in prowlarr logs.

Since Jacktook is running on android on same network it treats outside of local address and hence requires authentication to be enabled.

In jacktoo it says connection adapter and below is error from prowlarr 
> Info|Prowlarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.

**Comment by Sam-Max** [comment]
What did you set on host field?

**Comment by dinjojo** [comment]
> What did you set on host field?

Ip of host:9696

Problem is prowlarr doesnt allow calling its api without authentication

**Comment by Sam-Max** [comment]
> > What did you set on host field?
> 
> Ip of host:9696
> 
> Problem is prowlarr doesnt allow calling its api without authentication

the api key is for authentication. did you use http://ip:port?

**Comment by dinjojo** [comment]
Yes apikey is specified

**Comment by Sam-Max** [comment]
> Yes apikey is specified

and on the host did you set using http://ip:port?

**Comment by dinjojo** [comment]
![20240506_190615_1](https://github.com/Sam-Max/plugin.video.jacktook/assets/11513030/e02dfae1-65b5-47c9-8e5b-6b61bcb64548)

**Comment by dinjojo** [comment]
Got it working the http part was missing

**Comment by dinjojo** [comment]
Seems like it triggered lot of downloading of torrent via prowlarr this could be trouble 
![Screenshot_20240506_202930_Telegram](https://github.com/Sam-Max/plugin.video.jacktook/assets/11513030/ad63f3ea-4d0e-4e11-bd5f-e210404670dc)

**Comment by Sam-Max** [comment]
![image](https://github.com/Sam-Max/plugin.video.jacktook/assets/91879416/5cf1458c-5488-4c1f-b4c0-a0ffe31f0f7d)

**Comment by dinjojo** [comment]
Thanks for clarification
