### ISSUE TITLE
Jacktool 0..2.5

### ISSUE THREAD

**Issue by Marinem65** [Sam-Max/plugin.video.jacktook#42]
Hello,
Since yesterday, I have had problems with jacktook. I tried to reinstall but impossible since it says script.otaku.mappings not available and thus no installation.
This is my favorite addon so I would really appreciate it if you can help. Thanks!

**Comment by Marinem65** [comment]
Fixed.downloades okatu 👍

**Comment by Sam-Max** [comment]
oh sorry I need to add script.otaku.mappings to jacktook repository.

**Comment by Sam-Max** [comment]
> Fixed.downloades okatu 👍

I will add to jacktook repository so no need to install Otaku in the future

**Comment by ronfrankhill** [comment]
I am enjoying Jacktook. Keep up the great work with it @Sam-Max

**Comment by Marinem65** [comment]
Thanks! Great addon!
