### ISSUE TITLE
Addon won't launch

### ISSUE THREAD

**Issue by ambulancePilot** [Sam-Max/plugin.video.jacktook#43]
`2024-05-14 17:02:52.784 T:1704 error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/`

`2024-05-14 17:02:52.785 T:13304 error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/) failed`

I am getting this error in log no matter what I do. I can't even click authorize for RD.

Really want to use this addon. Please let me know what info you need from me. I already sorted through the Otaku Mappings issue by downloading the zip separately and installing.

Thank you so much.

**Comment by Sam-Max** [comment]
Hi @ambulancePilot but the addon is opening right? Only happens when you click on rd authorize?

**Comment by ambulancePilot** [comment]
Hi @Sam-Max, no the add-on doesn't open. It gives an error then says check log. I have tried many times to install, including on a clean Omega.

I even installed the Otaku again before Jacktook to make sure the dependency would install properly, but Jacktook will still not open. 

Any help would be appreciated. Your repo is Ajay generating errors in my log file for using HTTP she not HTTPS. Is that my issue or yours? 

Thank you so much.

**EDIT** — I'll generate a debug log for you showing me trying to open the add-on.

**Comment by Sam-Max** [comment]
can you send me the logs here https://t.me/sammax09?
