### ISSUE TITLE
Apple TV sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by Ade-AV** [Sam-Max/plugin.video.jacktook#44]
Getting this message popup regularly whilst using jacktook on Apple TV, doesn't seem to be affecting operation

**Comment by Sam-Max** [comment]
> Getting this message popup regularly whilst using jacktook on Apple TV, doesn't seem to be affecting operation

Its seems an issue with the python environment used by kodi. Which kodi version are you using?

**Comment by Ade-AV** [comment]
Hi, still getting this issue, I'm on 21.1

https://paste.kodi.tv/ehevuhanop
