### ISSUE TITLE
Multiples indexers

### ISSUE THREAD

**Issue by Gl17chV** [Sam-Max/plugin.video.jacktook#45]
First of all, thank you, Sam, for taking the time to create this addon. It quickly became one of my favorites due to its extensive range of indexers! Because of this, I find it hard to choose just one since I use several. I was wondering if it's possible to add a feature to search across different selected indexers. 

I mainly use Plex, Burst, and Torrentio. For security and connection reasons, I use TorServer for torrents, and I would really like to combine them to move away from Elementum.

**Comment by Sam-Max** [comment]
> First of all, thank you, Sam, for taking the time to create this addon. It quickly became one of my favorites due to its extensive range of indexers! Because of this, I find it hard to choose just one since I use several. I was wondering if it's possible to add a feature to search across different selected indexers.
> 
> I mainly use Plex, Burst, and Torrentio. For security and connection reasons, I use TorServer for torrents, and I would really like to combine them to move away from Elementum.

Not planning to do that for now. It needs a lot of rewrite and refactor of code.
