### ISSUE TITLE
Search Feature 

### ISSUE THREAD

**Issue by ronfrankhill** [Sam-Max/plugin.video.jacktook#46]
The search feature for movies or TV shows don't work within it.

**Comment by Sam-Max** [comment]
> The search feature for movies or TV shows don't work within it.

Hi, can you explain better what you mean?

**Comment by ronfrankhill** [comment]
When l tried to do an individual search in Jacktook for a particular show or movie within direct search section. It can't find it no matter if it past or recent TV show or movie e.g. The Lord of the Rings: The Rings of Power, Ophan Black: Echo. Just some of the examples. Instead l have to go through the long list within TV shows section to find what l am looking for.

**Comment by Sam-Max** [comment]
> When l tried to do an individual search in Jacktook for a particular show or movie within direct search section. It can't find it no matter if it past or recent TV show or movie e.g. The Lord of the Rings: The Rings of Power, Ophan Black: Echo. Just some of the examples. Instead l have to go through the long list within TV shows section to find what l am looking for.

What JT version are you using and what indexer are you using for the direct search?

**Comment by ronfrankhill** [comment]
I am using the latest version 0.2.6
I just type the name of what l am looking for within the add-on in the section direct search. I don't know if doing something wrong. Other add-ons there would option to search for TV section and other for movie. Jacktook has only direct search.

**Comment by Sam-Max** [comment]
> I am using the latest version 0.2.6 I just type the name of what l am looking for within the add-on in the section direct search. I don't know if doing something wrong. Other add-ons there would option to search for TV section and other for movie. Jacktook has only direct search.

On direct search section you have three options tv, movie, and search. And what indexer are you using to do the search?

**Comment by ronfrankhill** [comment]
TV Search. Just tried it again. No results found.

**Comment by Sam-Max** [comment]
> TV Search

but the indexer you are using, prowlarr, jackett, burst?

**Comment by Sam-Max** [comment]
> TV Search. Just tried it again. No results found.

but the indexer you are using, prowlarr, jackett, burst?

**Comment by ronfrankhill** [comment]
Torrentio

**Comment by Sam-Max** [comment]
> Debrid

Debrid is the client/player not the indexer. Look for the indexer you are using on the addon settings

**Comment by ronfrankhill** [comment]
Torrentio

**Comment by Sam-Max** [comment]
> Torrentio

Torrentio is not supported for direct search. A pop-up message should show saying that

**Comment by ronfrankhill** [comment]
Okay. Thanks.

**Comment by Sam-Max** [comment]
> Okay. Thanks.

For direct search the options are jackett, prowlarr or jacktook burst. Torrentio/elfhosted you can use on Search section that uses tmdb to look for titles, but not on direct search.

**Comment by ronfrankhill** [comment]
Okay. Thanks. I thought that l would use the direct search to find things faster instead of looking for something in the long list of TV shows and movies. Thanks for the education. Still learning about the add-on or plugging.

**Comment by ronfrankhill** [comment]
I even installed JackTorr. Just in case the add-on or plugging needs it.
