### ISSUE TITLE
Update: Jacktook 

### ISSUE THREAD

**Issue by ronfrankhill** [Sam-Max/plugin.video.jacktook#48]
I am getting update pop up for Jacktook but Jacktook isn't updating from the repo. I am on version 0.2.6 and the repo don't have the update.
I tried to update within the Jacktook 
settings. It will say update error. It will say that l have to do it manually.

**Comment by Sam-Max** [comment]
> I am getting update pop up for Jacktook but Jacktook isn't updating from the repo. I am on version 0.2.6 and the repo don't have the update. I tried to update within the Jacktook settings. It will say update error. It will say that l have to do it manually.

Yes, as version 0.2.6 has a bug on update code, it won't be able to update, you have to do it manually. From version 0.2.7 onwards the update will work fine.

**Comment by ronfrankhill** [comment]
So where can l get the latest version from? If it's not in your repo? Please.

**Comment by akistigas** [comment]
> > I am getting update pop up for Jacktook but Jacktook isn't updating from the repo. I am on version 0.2.6 and the repo don't have the update. I tried to update within the Jacktook settings. It will say update error. It will say that l have to do it manually.
> 
> Yes, as version 0.2.6 has a bug on update code, it won't be able to update, you have to do it manually. From version 0.2.7 onwards the update will work fine.

Hey there, where can we get version 0.2.7 from? Thanks a lot

**Comment by akistigas** [comment]
Hi there, can you please tell us where can we get version 0.2.7?

**Comment by Sam-Max** [comment]
> So where can l get the latest version from? If it's not in your repo? Please.

I already released the zip file for version 0.2.7. But you can always download the repository as a zip file and will be the same.

**Comment by ronfrankhill** [comment]
Okay. Thanks. I just installed the latest version 0.2.7 but when will version 0.2.8 be available.
