### ISSUE TITLE
Burst not working(?)

### ISSUE THREAD

**Issue by ladoba** [Sam-Max/plugin.video.jacktook#49]
Hi @Sam-Max .
Fresh installed Windows 10 VM w/ rdp,fresh installed jacktook,only 1 private tracker w/ burst,jacktorr.I tried movie,tv show,,direct search,tried search ,but it did not work at all.do you have any idea what could be wrong?Here is my log.
[kodi.log](https://github.com/user-attachments/files/16045201/kodi.log)

**Comment by Sam-Max** [comment]
> Hi @Sam-Max . Fresh installed Windows 10 VM w/ rdp,fresh installed jacktook,only 1 private tracker w/ burst,jacktorr.I tried movie,tv show,,direct search,tried search ,but it did not work at all.do you have any idea what could be wrong?Here is my log. [kodi.log](https://github.com/user-attachments/files/16045201/kodi.log)

It is working for me. Did you update to latest jacktook burst version 0.0.88?

**Comment by ladoba** [comment]
> > Hi @Sam-Max . Fresh installed Windows 10 VM w/ rdp,fresh installed jacktook,only 1 private tracker w/ burst,jacktorr.I tried movie,tv show,,direct search,tried search ,but it did not work at all.do you have any idea what could be wrong?Here is my log. [kodi.log](https://github.com/user-attachments/files/16045201/kodi.log)
> 
> It is working for me. Did you update to latest jacktook burst version 0.0.88?


Yes,I did.

**Comment by Sam-Max** [comment]
> > > Hi @Sam-Max . Fresh installed Windows 10 VM w/ rdp,fresh installed jacktook,only 1 private tracker w/ burst,jacktorr.I tried movie,tv show,,direct search,tried search ,but it did not work at all.do you have any idea what could be wrong?Here is my log. [kodi.log](https://github.com/user-attachments/files/16045201/kodi.log)
> > 
> > 
> > It is working for me. Did you update to latest jacktook burst version 0.0.88?
> 
> Yes,I did.

Write me here https://t.me/sammax09 to explain me more in details your problem

**Comment by ladoba** [comment]
> > > > Hi @Sam-Max . Fresh installed Windows 10 VM w/ rdp,fresh installed jacktook,only 1 private tracker w/ burst,jacktorr.I tried movie,tv show,,direct search,tried search ,but it did not work at all.do you have any idea what could be wrong?Here is my log. [kodi.log](https://github.com/user-attachments/files/16045201/kodi.log)
> > > 
> > > 
> > > It is working for me. Did you update to latest jacktook burst version 0.0.88?
> > 
> > 
> > Yes,I did.
> 
> Write me here https://t.me/sammax09 to explain me more in details your problem

I uninstalled kodi,delete kodi folder in appdata,fresh install kodi 20.5,jacktook 0.2.8,jacktook burst 0.0.88, jacktorr 0.0.1
Same problem.I did not touch kodi's setting.
[kodi.log](https://github.com/user-attachments/files/16045372/kodi.log)

**Comment by Sam-Max** [comment]
Closing this as it is fixed on new burst update
