### ISSUE TITLE
Jacktook Burst returns different number of results when compared to Elementum Burst.

### ISSUE THREAD

**Issue by saucepanlid** [Sam-Max/plugin.video.jacktook#52]
Hi there,

When using the Bitsearch Public Tracker in Jacktook Burst, I see a difference in the number of results when compared to Elementum Burst. Jacktook returns significantly less results when compared to Elementum. I tried enabling debug logging in the Jacktook Burst settings but it doesn't log additional messages to kodi.log so I can't compare the differences in the logs.

**Comment by Sam-Max** [comment]
> Hi there,
> 
> When using the Bitsearch Public Tracker in Jacktook Burst, I see a difference in the number of results when compared to Elementum Burst. Jacktook returns significantly less results when compared to Elementum. I tried enabling debug logging in the Jacktook Burst settings but it doesn't log additional messages to kodi.log so I can't compare the differences in the logs.

It happens with movies or tvshows?

**Comment by Sam-Max** [comment]
Closing this issue as many improvement on Jacktook Burst have been made since this was posted
