### ISSUE TITLE
Sort by seeders not working properly

### ISSUE THREAD

**Issue by saucepanlid** [Sam-Max/plugin.video.jacktook#53]
When using the Prowlerr, Jacket, Burst indexers and sorting results by seeders, the results are not correctly sorted properly and it seems that sorting is occurring on strings instead of being converted to integers first.

In sort_results (https://github.com/Sam-Max/plugin.video.jacktook/blob/main/lib/utils/general_utils.py#L761)

If I update 
`first_sorted = sorted(first_res, key=lambda r: r["seeders"], reverse=True)`

to

`first_sorted = sorted(first_res, key=lambda r: int(r["seeders"]), reverse=True)`

I get the desired results and results are sorted properly. However I am not sure if this is the best place to do this conversion.

**Comment by Sam-Max** [comment]
> When using the Prowlerr, Jacket, Burst indexers and sorting results by seeders, the results are not correctly sorted properly and it seems that sorting is occurring on strings instead of being converted to integers first.
> 
> In sort_results (https://github.com/Sam-Max/plugin.video.jacktook/blob/main/lib/utils/general_utils.py#L761)
> 
> If I update `first_sorted = sorted(first_res, key=lambda r: r["seeders"], reverse=True)`
> 
> to
> 
> `first_sorted = sorted(first_res, key=lambda r: int(r["seeders"]), reverse=True)`
> 
> I get the desired results and results are sorted properly. However I am not sure if this is the best place to do this conversion.

Make a PR with this fix too.
