### ISSUE TITLE
is_torrent_url Slow

### ISSUE THREAD

**Issue by saucepanlid** [Sam-Max/plugin.video.jacktook#55]
Significant time is spent on this function when there are many results that need to be fetched. Due to the network traffic generated maybe towards a CDN like cloudflare, its possible to trip up rate limiters or bot heuristics.

Additionally if the content-type header is all that's necessary, it a small optimisation to use HEAD instead of GET.

**Comment by Sam-Max** [comment]
> Significant time is spent on this function when there are many results that need to be fetched. Due to the network traffic generated maybe towards a CDN like cloudflare, its possible to trip up rate limiters or bot heuristics.
> 
> Additionally if the content-type header is all that's necessary, it a small optimisation to use HEAD instead of GET.

Yes, you are right a HEAD will be more efficient, since it doesn't download the response body, just the headers. Please make  a PR and I will merge it.
