### ISSUE TITLE
Direct search with Prowlarr not working

### ISSUE THREAD

**Issue by kiskey** [Sam-Max/plugin.video.jacktook#56]
Hi Sam,

First of all thanks so much for putting effort and time to develop this wonderfully addon and sharing with us. I really appreciate your effort 

I have setup latest jacktoo addon from jacktookrepo version 0.0.5.zip  and jacktook version 0.3.0,  with elementum player and prowlarr indexer service.i have configured prowlarr http://host:port with API key. I have not given any indexerid . As I have configured prowlarr with 1 indexer only  . 

I have been trying to use direct search .

I see the search term is showing up in prowlarr history and results in prowlarr. But the jacktoo addon throws "Invalid URL .No scheme provided ,you meant https://<magnethash>

I verified that the hash displayed in error as http://<magnethash>, is one of the magnet hash in the prowlarr's search results .    It looks jacktoo hits the prowlarr and return results ,just that it's not displaying all the results returned in jacktoo UI search result

Might be jacktook is not parsing the results rightly .

Please let me know .

**Comment by Sam-Max** [comment]
> Hi Sam,
> 
> First of all thanks so much for putting effort and time to develop this wonderfully addon and sharing with us. I really appreciate your effort
> 
> I have setup latest jacktoo addon from jacktookrepo version 0.0.5.zip and jacktook version 0.3.0, with elementum player and prowlarr indexer service.i have configured prowlarr http://host:port with API key. I have not given any indexerid . As I have configured prowlarr with 1 indexer only .
> 
> I have been trying to use direct search .
> 
> I see the search term is showing up in prowlarr history and results in prowlarr. But the jacktoo addon throws "Invalid URL .No scheme provided ,you meant https://
> 
> I verified that the hash displayed in error as http://, is one of the magnet hash in the prowlarr's search results . It looks jacktoo hits the prowlarr and return results ,just that it's not displaying all the results returned in jacktoo UI search result
> 
> Might be jacktook is not parsing the results rightly .
> 
> Please let me know .

I will make some test today, I have not used prowlarr for a while

**Comment by Sam-Max** [comment]
> at the hash displayed in error as http://, is one of the magnet hash in the prowlarr's search results . It looks jacktoo hits the prowlarr and return results ,just that it's not displaying all the results returned in jacktoo UI search result
> 
> Might be jacktook is not parsing the results rightly .

I tested now and worked fine. Can you write me here https://t.me/sammax08 to give me more details?

**Comment by kiskey** [comment]
Thanks Sam for identifying the issue. This issue is not linked to jacktook. As the prowlarr to self hosted indexer based u tegration is not officially supported . Was using Generic torznab integration with Prowlarr might be causing issue .    And also jackett seems to be officially supporting bitmagnet indexer. And jacktook works completely fine with bitmagnet jackett  based direct search .


Thanks again for this wonderful addon 👍
