### ISSUE TITLE
[req] Debrid services "Pikpak"

### ISSUE THREAD

**Issue by ericvlog** [Sam-Max/plugin.video.jacktook#57]
Can add pikpak as alternative debrid services for Asian stuff? pikpak well cache all torrent without delete even long time no active, it place in cold storage, and just need to activated old torrent.

Now only Mediafusion addons have this debrid services and it run well on Kodi, just the addon no make specific for kodi.

the addon use this for implement

https://github.com/Quan666/PikPakAPI

Thanks.

**Comment by Sam-Max** [comment]
Thanks for your suggestion, but not interested to add new debrid services for now.
