### ISSUE TITLE
Plex Support Removed

### ISSUE THREAD

**Issue by ohmichael** [Sam-Max/plugin.video.jacktook#62]
I’m curious because I used it tons with jacktook over the other addon composite for plex because it was much simpler but ever since the update it’s made me have to downgrade to previous version because I had a backup copy but the question is can you add plex support back please :( And when I’m in kodi it uses up alot of my time switching back and forth in the Android app of plex. Reason I asked. With the removal of plex basically until it’s added again I can’t update jacktook else I’ll lose plex support.

**Comment by Sam-Max** [comment]
Sorry dude, but I removed it because I'm trying to keep the addon as simple as possible and with the most used integrations, so I can maintain it more easily on my free time.  I hope you understand.
