### ISSUE TITLE
[FEATURE REQUEST] adding tracking support 

### ISSUE THREAD

**Issue by guybarner** [Sam-Max/plugin.video.jacktook#63]
I would love to have the ability to track the torrent I see in trakt/simkl/anilist

**Comment by Sam-Max** [comment]
Sorry, but not interested on doing that right now, maybe in the future. I am working on this project mainly because of personal use and share with others that may find it useful.

**Comment by jollyhiggler** [comment]
> I would love to have the ability to track the torrent I see in trakt/simkl/anilist

The addon supports scrobbling by the Trakt addon in the main Kodi repository.
