### ISSUE TITLE
[1.7] Type Error in premiumize_api

### ISSUE THREAD

**Issue by asylumexp** [Sam-Max/plugin.video.jacktook#8]
This error occurs for me whenever any action with the plugin is performed (authorising or trying to use the plugin):
2024-02-23 09:37:45.452 T:22460   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: unsupported operand type(s) for |: 'type' and 'type'
                                                   Traceback (most recent call last):
                                                     File "Kodi\addons\plugin.video.jacktook\jacktook.py", line 3, in <module>
                                                       from resources.lib.navigation import run
                                                     File "Kodi\addons\plugin.video.jacktook\resources\lib\navigation.py", line 4, in <module>
                                                       from resources.lib.api.premiumize_api import Premiumize
                                                     File "Kodi\addons\plugin.video.jacktook\resources\lib\api\premiumize_api.py", line 16, in <module>
                                                       class DebridClient:
                                                     File "Kodi\addons\plugin.video.jacktook\resources\lib\api\premiumize_api.py", line 85, in DebridClient
                                                       target_status: str | int,
                                                   TypeError: unsupported operand type(s) for |: 'type' and 'type'
                                                   -->End of Python script error report<--

**Comment by Sam-Max** [comment]
Which addon version are you using?. I tested again authorize to premiumize and works fine without anny issue. Also give more details about the steps that lead you to that error, to reproduce by myself.

**Comment by asylumexp** [comment]
Im using the latest addon version, tried the github version and the repository version in case there was a difference.

The steps i took from start to end was:
- Installed Kodi 20.4
- Installed the repository by downloading the zip from github
- Installed the plugin via the repository
- Configured it to use Debrid and Torrentio
- Inputted Premiumize api key and hit authorise

Also to note, I accidentally clicked on the addon before configuring it, and it still said the same error, even when it wasn't configured to use debrid or to authorise yet.

**Comment by asylumexp** [comment]
> Im using the latest addon version, tried the github version and the repository version in case there was a difference.
> 
> The steps i took from start to end was:
> 
> * Installed Kodi 20.4
> * Installed the repository by downloading the zip from github
> * Installed the plugin via the repository
> * Configured it to use Debrid and Torrentio
> * Inputted Premiumize api key and hit authorise
> 
> Also to note, I accidentally clicked on the addon before configuring it, and it still said the same error, even when it wasn't configured to use debrid or to authorise yet.

Tried also on Kodi 19.5, same error.

Only thing I could think of is the version of Python installed on my machine, but I wouldn't know if it uses an included version of Python that comes with Kodi or otherwise. I could try install another version if you tell me which one you have installed? (I have 3.11 installed).

**Comment by Sam-Max** [comment]
Don't input manually Premiumize api key, leave blank the field. Just click authorize and when process is finished, the api key will be filled automatically.

**Comment by asylumexp** [comment]
Found out the issue, its that it was running with Python 3.8, I'm assuming this was bundled in with Kodi, which is what causes it to crash, as [str | int](https://github.com/Sam-Max/plugin.video.jacktook/blob/e68f2798382abbaa81a34d9b2c574a1bea806a14/resources/lib/api/premiumize_api.py#L85) isn't available until 3.10, also had errors for [-> dict[str, Any] | None](https://github.com/Sam-Max/plugin.video.jacktook/blob/e68f2798382abbaa81a34d9b2c574a1bea806a14/resources/lib/api/premiumize_api.py#L291) and [torrent_hashes: list[str]](https://github.com/Sam-Max/plugin.video.jacktook/blob/e68f2798382abbaa81a34d9b2c574a1bea806a14/resources/lib/api/premiumize_api.py#L278C48-L278C73).

I'm assuming theres a way to get a newer version of python for Kodi to use or for it to use the system version. But if there isn't these lines should probably be changed, or at least have something in the readme about them.

**Comment by asylumexp** [comment]
I fixed it for myself by changing `str | int ` to `Union[str, int]` from typing, then deleted the other two that were causing issues

**Comment by Sam-Max** [comment]
Make a pull request with those fixes if you can, I would appreciate.
