### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by bjgood** [Sam-Max/plugin.video.jacktook#9]
Hi,
It would nice to see a download feature included.
Thanks.
Later...

**Comment by Sam-Max** [comment]
Download to debrid or local?

**Comment by bjgood** [comment]
Thanks for the reply.
Locally.
Later...

**Comment by addon-rajada** [comment]
@bjgood 

I believe you can download files locally using Torrest by now. Don't know about debrid.

**Comment by asylumexp** [comment]
If #12 is merged, then you can download to local disk by setting a download directory in the elementum settings then when playing a file, hit cancel and tell it to continue to download and itll download locally.
